# Generated by Django 5.1 on 2024-09-07 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto', models.DateTimeField(auto_now_add=True)),
                ('categoria_gasto', models.CharField(max_length=50)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administradores.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='InformeTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_donaciones', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_gastos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administradores.administrador')),
            ],
        ),
    ]
