# Generated by Django 5.1 on 2024-11-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donantes', '0002_remove_donante_usuario_donante_aceptacion_privacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='contraseña',
            field=models.CharField(default='12345', max_length=128),
            preserve_default=False,
        ),
    ]
