# Generated by Django 5.1 on 2024-11-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donantes', '0003_donante_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donante',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
