# Generated by Django 5.1 on 2024-10-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('datos_personales', models.TextField()),
                ('domicilio', models.TextField()),
                ('estado_beca', models.CharField(max_length=50)),
                ('estudio_socioeconomico', models.TextField()),
                ('informacion_academica', models.TextField()),
                ('informacion_beca', models.TextField()),
                ('renovaciones_beca', models.TextField()),
            ],
        ),
    ]
