# Generated by Django 5.1 on 2024-09-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('comentario', models.TextField()),
                ('fecha_apertura', models.DateField()),
                ('fecha_limite_inscripcion', models.DateField()),
                ('fecha_resultados', models.DateField()),
                ('duracion_programa', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaParticipacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Convocatorias.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionConvocatoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Convocatorias.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoParticipacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requisito', models.TextField()),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Convocatorias.convocatoria')),
            ],
        ),
    ]
