# Generated by Django 5.1 on 2024-10-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0004_convocatoria_limite_becarios_convocatoria_monto_beca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='cantidad_becarios',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
