# Generated by Django 5.1 on 2024-10-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0006_remove_convocatoria_limite_becarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
