# Generated by Django 5.1 on 2024-10-15 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField()),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voluntarios.voluntario')),
            ],
        ),
    ]
