# Generated by Django 5.1 on 2024-11-27 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Becarios', '0014_alter_documentosacademicos_grado_estudio'),
        ('Voluntarios', '0003_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('becario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Becarios.becario')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voluntarios.programa')),
            ],
        ),
    ]
