# Generated by Django 5.1 on 2024-09-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='2005-01-30', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='curp',
            field=models.CharField(default='2005-01-30', max_length=18, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(default='2005-01-30', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(default='2005-01-30', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rfc',
            field=models.CharField(default='2005-01-30', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='2005-01-30', max_length=15),
            preserve_default=False,
        ),
    ]
