# Generated by Django 5.1 on 2024-09-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_usuario_apellidos_usuario_curp_usuario_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curp',
            field=models.CharField(max_length=18),
        ),
    ]
