# Generated by Django 5.1 on 2024-09-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_usuario_curp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='apellido_materno',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
