# Generated by Django 5.1 on 2024-09-07 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Becario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_actual', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('rfc', models.CharField(max_length=13)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('becario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Becarios.becario')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=50)),
                ('becario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Becarios.becario')),
            ],
        ),
    ]
