# Generated by Django 5.1 on 2024-09-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Becarios', '0002_informacionacademica_informacionbeca_usuario_and_more'),
        ('Usuarios', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='becario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Coordinador',
        ),
        migrations.DeleteModel(
            name='Donante',
        ),
        migrations.DeleteModel(
            name='Voluntario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
