# Generated by Django 5.1 on 2024-09-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Becarios', '0003_remove_coordinador_usuario_remove_donante_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosPersonales',
        ),
    ]
