# Generated by Django 5.1 on 2024-09-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Becarios', '0005_alter_becario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becario',
            name='estado_actual',
        ),
    ]
