# Generated by Django 5.1 on 2024-09-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Becarios', '0006_remove_becario_estado_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionacademica',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informacionacademica',
            name='fecha_ingreso',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
