# Generated by Django 5.1 on 2024-10-06 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Becarios', '0007_informacionacademica_fecha_egreso_and_more'),
        ('Convocatorias', '0002_convocatoria_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='becario',
            name='convocatoria',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='Convocatorias.convocatoria'),
            preserve_default=False,
        ),
    ]
