# Generated by Django 5.1 on 2024-11-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Becarios', '0009_alter_becario_convocatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosAcademicos',
            fields=[
                ('becario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Becarios.becario')),
                ('constancia', models.FileField(blank=True, null=True, upload_to='documentos/constancias/')),
                ('boleta', models.FileField(blank=True, null=True, upload_to='documentos/boletas/')),
                ('grado_estudio', models.IntegerField()),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('promedio_semestre', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusDocumentacion',
            fields=[
                ('documentos_academicos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Becarios.documentosacademicos')),
                ('estatus_constancia', models.CharField(max_length=20)),
                ('estatus_boleta', models.CharField(max_length=20)),
                ('comentarios_constancia', models.TextField(blank=True, null=True)),
                ('comentarios_boleta', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
