# Generated by Django 5.1 on 2024-11-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Becarios', '0011_alter_documentosacademicos_grado_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionacademica',
            name='grado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informacionacademica',
            name='tipo_periodo',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
    ]
