# Generated by Django 5.1 on 2024-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Becarios', '0012_informacionacademica_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosacademicos',
            name='grado_estudio',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
